### PR TITLE
Camelize name components in generated types

### LINKED ISSUE #252: Lowercase enums generate wrong typespecs
when generating elixir code, the generated defmodule starts with an uppercase, but the reference to the type has a lowercase:

in the proto file:

```
enum valueType {
    VALUE_TYPE_UNDEFINED = 0;  // used for null, meaning: in the given timeframe CAN data was unavailable
    VALUE_TYPE_INTEGER   = 1;
    VALUE_TYPE_FLOAT     = 2;
    VALUE_TYPE_STRING    = 3;
}

....
```

The generated defmodule:

```
defmodule Police.Protos.ValueType do
  @moduledoc false
  use Protobuf, enum: true, syntax: :proto2

  @type t ::
          integer
          | :VALUE_TYPE_UNDEFINED
          | :VALUE_TYPE_INTEGER
          | :VALUE_TYPE_FLOAT
          | :VALUE_TYPE_STRING

  field :VALUE_TYPE_UNDEFINED, 0
  field :VALUE_TYPE_INTEGER, 1
  field :VALUE_TYPE_FLOAT, 2
  field :VALUE_TYPE_STRING, 3
end

defmodule Police.Protos.DataSeries do
  @moduledoc false
  use Protobuf, syntax: :proto2

  @type t :: %__MODULE__{
          id: non_neg_integer,
          type: Police.Protos.valueType().t(),
         ...
        }

  defstruct id: nil,
            type: nil,
            samplingPeriod: nil,
            lastSampleOffset: nil,
            valueSet: []

  field :id, 1, optional: true, type: :uint32
  field :type, 2, optional: true, type: Police.Protos.valueType(), enum: true
  ...
end
```

I think this
``` type: Police.Protos.valueType().t(),```
should be
``` type: Police.Protos.ValueType.t(),```

and 
```field :type, 2, optional: true, type: Police.Protos.valueType(), enum: true```
should be
```field :type, 2, optional: true, type: Police.Protos.ValueType, enum: true```

to have valid elixir.

### PR DESCRIPTION
**Pull request by whatyouhide**
Closes #252.

### CODE REVIEW

File: lib/protobuf/protoc/cli.ex [hunk 1]
```diff
@@ -118,8 +118,8 @@ defmodule Protobuf.Protoc.CLI do
   @doc false
   def find_types(%Context{} = ctx, descs) do
     global_type_mapping =
-      Map.new(descs, fn desc ->
-        {desc.name, find_types_in_proto(ctx, desc)}
+      Map.new(descs, fn %Google.Protobuf.FileDescriptorProto{name: filename} = desc ->
```
Comment (whatyouhide) [inline lib/protobuf/protoc/cli.ex:121]: All refactors in this file

File: lib/protobuf/protoc/generator/message.ex [hunk 2]
```diff
@@ -164,13 +164,13 @@ defmodule Protobuf.Protoc.Generator.Message do
...
+      type when type in [:enum, :message] and not is_nil(type_name) ->
+        Util.type_from_type_name(ctx, type_name)
 
-    if f.type_name && (type == :enum || type == :message) do
-      Util.type_from_type_name(ctx, f.type_name)
-    else
-      ":#{type}"
+      type ->
+        inspect(type)
     end
```
Comment (whatyouhide) [inline lib/protobuf/protoc/generator/message.ex:174]: Refactor

File: lib/protobuf/protoc/generator/util.ex [hunk 3]
```diff
@@ -9,10 +9,15 @@ defmodule Protobuf.Protoc.Generator.Util do
...
-    end
+    ns = Enum.map(ns, &proto_name_to_module_name/1)
+
+    parts =
+      case camelcase_prefix(ctx) do
+        "" -> ns
+        prefix -> [prefix | ns]
+      end
+
+    Enum.join(parts, ".")
```
Comment (whatyouhide) [inline lib/protobuf/protoc/generator/util.ex:20]: The Fix™

File: test/protobuf/protoc/cli_integration_test.exs [hunk 4]
```diff
@@ -82,6 +82,34 @@ defmodule Protobuf.Protoc.CLIIntegrationTest do
       assert [mod] = compile_file_and_clean_modules_on_exit("#{tmp_dir}/user.pb.ex")
       assert mod == Mypkg.Foo.User
     end
+
+    # Regression test for https://github.com/elixir-protobuf/protobuf/issues/252
```
Comment (whatyouhide) [inline test/protobuf/protoc/cli_integration_test.exs:86]: Test for said fix
