### PR TITLE
Fix bug with decoding varints

### LINKED ISSUE #205: Fix FunctionClauseError when decoding varints
This error can be brought up by running the conformance tests after removing some of the exempted tests.

The error is pretty much always this:

```
** (FunctionClauseError) no function clause matching in Protobuf.Decoder.decode_varints/3
    (protobuf 0.8.0) lib/protobuf/decoder.ex:201: Protobuf.Decoder.decode_varints(0, :bool, [])
    (protobuf 0.8.0) lib/protobuf/decoder.ex:134: Protobuf.Decoder.handle_value/6
    (protobuf 0.8.0) lib/protobuf/decoder.ex:17: Protobuf.Decoder.decode/2
    (protobuf 0.8.0) conformance/protobuf/runner.ex:110: Conformance.Protobuf.Runner.safe_decode/2
    (protobuf 0.8.0) conformance/protobuf/runner.ex:78: Conformance.Protobuf.Runner.handle_conformance_request/1
    (protobuf 0.8.0) conformance/protobuf/runner.ex:28: Conformance.Protobuf.Runner.loop/0
    (elixir 1.12.1) lib/kernel/cli.ex:124: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

This is just one of the many conformance tests that trigger this error: `Required.Proto3.ProtobufInput.ValidDataRepeated.BOOL.UnpackedInput.ProtobufOutput`.

### PR DESCRIPTION
**Pull request by whatyouhide**
Not sure if this is a _good_ way to do it, but it fixes a bunch of conformance tests and doesn't break any of them :sweat_smile:

Closes #205.

### CODE REVIEW

File: lib/protobuf/decoder.ex [hunk 1]
```diff
@@ -198,6 +198,10 @@ defmodule Protobuf.Decoder do
     end
   end
 
+  defp decode_varints(n, type, acc) when is_integer(n) do
+    [Wire.to_proto(type, n) | acc]
+  end
+
```
Comment (whatyouhide) [inline lib/protobuf/decoder.ex:204]: This seems to be the fix. We already get an integer here, not a binary.

File: lib/protobuf/wire/varint.ex [hunk 2]
```diff
@@ -173,10 +173,7 @@ defmodule Protobuf.Wire.Varint do
         end
 
       quote do
-        case unquote(kind) do
-          :def -> def unquote(head), do: unquote(body)
-          :defp -> defp unquote(head), do: unquote(body)
-        end
+        Kernel.unquote(kind)(unquote(head), do: unquote(body))
```
Comment (whatyouhide) [inline lib/protobuf/wire/varint.ex:176]: Just a small refactor.

File: lib/protobuf/decoder.ex (hunk 1 above)
Comment (ericmj) [reply lib/protobuf/decoder.ex:204]: It seems strange that we get an integer when all other clauses expect an integer.

**Comment by ericmj** [comment]
Can you add a unit test for this that is not a conformance test?

File: conformance/exemptions.txt [hunk 3]
```diff
@@ -625,33 +613,18 @@ Required.Proto3.ProtobufInput.RepeatedScalarSelectsLast.ENUM.JsonOutput
...
 Required.Proto3.ProtobufInput.ValidDataRepeated.ENUM.UnpackedInput.JsonOutput
-Required.Proto3.ProtobufInput.ValidDataRepeated.ENUM.UnpackedInput.ProtobufOutput
-Required.Proto3.ProtobufInput.ValidDataRepeated.INT32.UnpackedInput.JsonOutput
-Required.Proto3.ProtobufInput.ValidDataRepeated.INT32.UnpackedInput.ProtobufOutput
-Required.Proto3.ProtobufInput.ValidDataRepeated.INT64.UnpackedInput.JsonOutput
-Required.Proto3.ProtobufInput.ValidDataRepeated.INT64.UnpackedInput.ProtobufOutput
 Required.Proto3.ProtobufInput.ValidDataRepeated.SINT32.PackedInput.JsonOutput
 Required.Proto3.ProtobufInput.ValidDataRepeated.SINT32.PackedInput.ProtobufOutput
 Required.Proto3.ProtobufInput.ValidDataRepeated.SINT32.UnpackedInput.JsonOutput
 Required.Proto3.ProtobufInput.ValidDataRepeated.SINT32.UnpackedInput.ProtobufOutput
```
Comment (britto) [inline conformance/exemptions.txt:627]: It's odd that this fixes `SINT64` but not `SINT32`. Better have a closer look 🔍.

Comment (britto) [reply conformance/exemptions.txt:627]: OK. I think I've got it. According to [the docs](https://developers.google.com/protocol-buffers/docs/encoding#packed), we have to be more lenient on decoding:

> Protocol buffer parsers must be able to parse repeated fields that were compiled as packed as if they were not packed, and vice versa. This permits adding `[packed=true]` to existing fields in a forward- and backward-compatible way.

This means we'll probably need to generalize our exemption from just varints to pretty much any repeated field. Making sure we decode properly even when they are declared as packed but not encoded as such. And vice-versa 🤯.

Comment (britto) [reply conformance/exemptions.txt:627]: Basically, treat the `packed` flag more like a "hint" to what the input should look like.

Since this is the exception, not the rule, I'd consider pushing this case (input/definition mismatch) down to the bottom of any pattern-matching chain covering it, so we don't compromise the performance too much in the general case.

Comment (britto) [reply conformance/exemptions.txt:599]: @whatyouhide has the list shrunk further with that general approach?

**Review by britto — APPROVED** [review]

File: conformance/exemptions.txt (hunk 3 above)
Comment (whatyouhide) [reply conformance/exemptions.txt:599]: Nope :)
