### PR TITLE
Fixes typespecs for proto3_optional fields

### LINKED ISSUE #312: generated typespec doesn't seem to take `proto3_optional: true` into account

### PR DESCRIPTION
**Pull request by antedeguemon**
Hey folks! 🖖 

Typespecs for fields with `proto3_optional` flag are missing `nil` as a possible value. This pull request fixes the issue by including `nil` as a possible typespec value when a field has the `proto3_optional` flag enabled. 

Closes #312.

### Scenario

Consider the proto3 message with an optional field: 

```proto
syntax = "proto3";
// ...
message Person {
  optional int32 identifier = 1;
}
```

Currently, the following type is generated for the above message:

```elixir
@type t :: %Person{
  identifier: integer(), # <-- note it is missing `| nil`, as `identifier` is optional 
  __unknown_fields__: [...]
}
```

After this pull request, typespecs for `optional` fields in proto3 will include `nil` as a possible value:

```elixir
@type t :: %Person{ 
  identifier: integer() | nil, 
  __unknown_fields__: [...]
}
```

### CODE REVIEW

File: lib/protobuf/dsl/typespecs.ex [hunk 1]
```diff
@@ -80,7 +80,8 @@ defmodule Protobuf.DSL.Typespecs do
       prop.repeated? ->
         quote do: [unquote(spec)]
 
-      prop.embedded? or (prop.optional? and is_nil(prop.oneof) and syntax != :proto3) ->
+      prop.embedded? or (prop.optional? and is_nil(prop.oneof) and syntax != :proto3) or
+          (prop.proto3_optional? and syntax == :proto3) ->
```
Comment (ericmj) [inline lib/protobuf/dsl/typespecs.ex:84]: Can `proto3_optional?` be true when `syntax != :proto3`?
```suggestion
          prop.proto3_optional? ->
```

**Review by ericmj — APPROVED** [review]

File: lib/protobuf/dsl/typespecs.ex (hunk 1 above)
Comment (antedeguemon) [reply lib/protobuf/dsl/typespecs.ex]: Opss, you are right! `proto3_optional?` can only be true if the message uses the proto3 syntax.

✔️ Fixed, thank you!
