### PR TITLE
Fix multiple conflicting PbExtension modules

### LINKED ISSUE #88: Multiple conflicting PbExtension modules
protobuf-elixir: 0.8.0-beta.1
elixir: 1.10.1
otp: 22.2.7

I am trying to compile [these .proto files](https://github.com/Cockatrice/Cockatrice/tree/master/common/pb) using version 0.8.0-beta.1, and in most of the resulting 155 elixir files I get a PbExtension module. Elixir can obviously only handle one module with a given name, so this fails to compile.

### PR DESCRIPTION
**Pull request by whatyouhide**
Closes #88.

The idea here is:

  * Generate one extension module per message, as suggested by @ericmj (https://github.com/elixir-protobuf/protobuf/issues/88#issuecomment-961293983)
  * For extensions defined at the `.proto` file level, we generate a unique module name like `<package>.Extensions<unique_int>.PbExtension`. The `<unique_int>` part is calculated by using `erlang:phash2/1` on the sorted list of extensions definitions in the file. That way it stays mostly the same when regenerating, module reordering them too.

### CODE REVIEW

File: lib/protobuf.ex [hunk 1]
```diff
@@ -282,7 +282,25 @@ defmodule Protobuf do
   """
   @spec load_extensions() :: :ok
   def load_extensions() do
-    Protobuf.Extension.__cal_extensions__()
+    for mod <- get_all_modules(),
```
Comment (whatyouhide) [inline lib/protobuf.ex:285]: Refactor: I just moved the `__cal_extensions__/0` function inline here, not sure why we kept it separate in another module.

File: lib/protobuf/dsl.ex [hunk 2]
```diff
@@ -28,9 +28,50 @@ defmodule Protobuf.DSL do
 
   @doc """
   Define extensions range in the message module to allow extensions for this module.
+
+  Extension ranges are defined as a list of tuples `{start, end}`, where each tuple is
```
Comment (whatyouhide) [inline lib/protobuf/dsl.ex:32]: Just docs and better errors.

File: lib/protobuf/extension.ex [hunk 3]
```diff
@@ -35,6 +35,25 @@ defmodule Protobuf.Extension do
...
+  ## Examples
+
+      iex> Protobuf.Extension.max()
+      #{inspect(@max)}
+
+  """
+  @doc since: "0.12.0"
+  @spec max() :: pos_integer()
+  def max, do: @max
+
```
Comment (whatyouhide) [inline lib/protobuf/extension.ex:56]: Small quality of life improvemenet.

File: lib/protobuf/protoc/generator/extension.ex [hunk 4]
```diff
@@ -19,43 +16,22 @@ defmodule Protobuf.Protoc.Generator.Extension do
...
-            syntax: ctx.syntax,
-            protoc_gen_elixir_version: "\"#{Util.version()}\""
-          })
-
-        {msg_name,
-         Util.format(
-           extension_template(module: msg_name, use_options: use_options, extends: extends)
-         )}
-    end
+  @spec generate(Context.t(), FileDescriptorProto.t()) ::
```
Comment (whatyouhide) [inline lib/protobuf/protoc/generator/extension.ex:19]: The Fixes™ are all in this file.

**Comment by whatyouhide** [comment]
Nope, it turns out the that `phash2`-based solution doesn't really work because the names need to be predictable since they're part of the public API for getting and setting extensions. Will **think** 🧠 a bit more. 🙃

**Comment by ericmj** [comment]
Would it be possible to collect all `extend Foo` and generate a single module for them to avoid collisions?

How do libraries for other languages solve this problem?

**Comment by whatyouhide** [comment]
I don't know how other libraries solve this. Collecting them... I'm not sure, because what if two libraries use the same Protobuf package? That would lead to the same module name I think.

However, I'm thinking I might be overthinking this, and maybe the solution is to change the API to get and put extension fields. For example, if I do `Protobuf.put_extension(..., Ext.MyModule, :some_field, _value = 1)` we could translate that to the right `Ext.Extensions123456<...>.PbExtension`. Thoughts @ericmj?

**Comment by whatyouhide** [comment]
Merging this since It Works™ @ericmj, I'll do a pass of refactoring soon 🙃
