### PR TITLE
Fix JSON encoding map validation

### LINKED ISSUE #306: Should JSON encoding validate the Protobuf message as well?
For context: https://github.com/elixir-protobuf/protobuf/pull/301

At the moment they are two different behaviors between `MyMessage.encode/1` and `Protobuf.JSON.encode!`.

`MyMessage.encode/1` does validate the structure of the message, while `Protobuf.JSON.encode!` does not. See https://github.com/elixir-protobuf/protobuf/pull/301 for more context and examples.

This caused some issues where we are using Protobuf for some json-protobuf-driven API where we trusted we did it correctly because it didn't fail. Still, it was incorrect because we technically added the wrong data to it.

## Proposal

`Protobuf.JSON.encode!` should have the same behavior as `MyMessage.encode/1` and validate the structure of the JSON.

### PR DESCRIPTION
**Pull request by yordis**
Closes #306.

### CODE REVIEW

File: test/protobuf/protoc/generator_integration_test.exs [hunk 1]
```diff
@@ -48,6 +48,30 @@ defmodule Protobuf.Protoc.GeneratorIntegrationTest do
     end)
   end
 
+  test "encoding map<string, string> validates the input" do
+    input =
+      My.Test.CreateAccountRequest.new!(%{
+        account: %{
+          instance_param_vals: %{
+            levels: %{
```
Comment (ericmj) [inline test/protobuf/protoc/generator_integration_test.exs:56]: You are nesting the map inside another field, it should be directly under `instance_param_vals` or you need to change the schema.

Comment (yordis) [reply test/protobuf/protoc/generator_integration_test.exs:56]: @ericmj right, that is the issue, that we made the mistake of forgetting to marshall the `levels` (in this case) value to be a string rather than a map.

Notice that if I use the Protobuf serialize does work correctly, but if I use the JSON one, it doesn't.

Comment (ericmj) [reply test/protobuf/protoc/generator_integration_test.exs:56]: Can you fill out an issue that explains what happens now and what you would expect to happen?

Comment (yordis) [reply test/protobuf/protoc/generator_integration_test.exs:56]: @ericmj yeah, for sure! I focused on replicating the issue to prove my hypothesis than explaining about. The reason why it is in Draft mode and left a comment in the description.

I will do it as soon as I find some time for it.

Comment (ericmj) [reply test/protobuf/protoc/generator_integration_test.exs:56]: We don't have any validation for JSON encoding other than for the `Google.Protobuf.` prefixed schemas so this may be a pretty big feature to implement. The best thing may be to just call `Protobuf.encode` before JSON encoding, but it's better to discuss that in an issue.

Comment (yordis) [reply test/protobuf/protoc/generator_integration_test.exs:56]: > The best thing may be to just call Protobuf.encode before JSON encoding

Spot on, that is the question for sure here.

Do we want to do that?


Feels like a lot of extra overhead which is not a big deal for us, but for higher performance requirements may be suboptimal.

I am not sure.

**Comment by ericmj** [comment]
Reopening for implementation.

File: test/protobuf/protoc/generator_integration_test.exs [hunk 2]
```diff
@@ -48,6 +48,49 @@ defmodule Protobuf.Protoc.GeneratorIntegrationTest do
...
+      %{key: :uint64_map, wrong_value: "not uint64", expected_type: :uint64},
+      %{key: :float_map, wrong_value: "not float", expected_type: :float},
+      %{key: :double_map, wrong_value: "not double", expected_type: :double},
+      %{key: :string_map, wrong_value: %{levels: %{level_1: 0.4}}, expected_type: :string},
+      %{key: :bool_map, wrong_value: "not bool", expected_type: :bool},
+      %{key: :bytes_map, wrong_value: 42, expected_type: :bytes},
+      %{key: :enum_map, wrong_value: "not an map enum value", expected_type: :enum, opts: [use_enum_numbers: false]},
+
+      # ASK: I got stuck here due to getting confused by https://github.com/elixir-protobuf/protobuf/blob/885f39e2eccd5468d885d62955fcf695ac6f1fce/lib/protobuf/json/encode.ex#L213
+      %{key: :enum_map, wrong_value: :NOT_VALID, expected_type: :enum, opts: [use_enum_numbers: true]},
```
Comment (yordis) [inline test/protobuf/protoc/generator_integration_test.exs:71]: @ericmj @whatyouhide hey peeps, I got stuck fixing the issue, I am getting the following issue

```
stacktrace:
       (protobuf 0.11.0) My.Test.MapEnum.value(:NOT_VALID)
       (protobuf 0.11.0) lib/protobuf/json/encode.ex:193: anonymous fn/5 in Protobuf.JSON.Encode.encode_value/3
       (stdlib 3.17.2) maps.erl:410: :maps.fold_1/3
       (protobuf 0.11.0) lib/protobuf/json/encode.ex:191: Protobuf.JSON.Encode.encode_value/3
       (protobuf 0.11.0) lib/protobuf/json/encode.ex:139: anonymous fn/4 in Protobuf.JSON.Encode.encode_regular_fields/3
       (stdlib 3.17.2) maps.erl:410: :maps.fold_1/3
       (protobuf 0.11.0) lib/protobuf/json/encode.ex:119: Protobuf.JSON.Encode.encode_regular_fields/3
       (protobuf 0.11.0) lib/protobuf/json/encode.ex:112: Protobuf.JSON.Encode.encodable/2
       (protobuf 0.11.0) lib/protobuf/json.ex:205: Protobuf.JSON.to_encodable/2
       (protobuf 0.11.0) lib/protobuf/json.ex:160: Protobuf.JSON.encode/2
       (protobuf 0.11.0) lib/protobuf/json.ex:110: Protobuf.JSON.encode!/2
       test/protobuf/protoc/generator_integration_test.exs:85: anonymous fn/2 in Protobuf.Protoc.GeneratorIntegrationTest."test encoding maps ensure that validates the input"/1
       (elixir 1.13.3) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
       test/protobuf/protoc/generator_integration_test.exs:82: (test)

```

I am not sure how I should be validating the enum because the comment confuses me in terms of what it meant and what to do

I would appreciate some help understanding what I should be doing for enum.

**Comment by whatyouhide** [comment]
@yordis I took the liberty to check this PR out locally, update tests and push the changes here. I also marked this as ready for review, and it looks good to me now! 🙃

**Comment by yordis** [comment]
@whatyouhide by all means take the lead unless you would like me to continue working on it. Thank you so much for the support with it

**Comment by whatyouhide** [comment]
@yordis is there anything left to do here, validation wise?

**Comment by yordis** [comment]
I think the package is quite complete, as far as I can tell. Maybe I should try to gather a list of all the data types supported by protobuf and validate that we covered them all.

**Comment by whatyouhide** [comment]
@yordis that would be fantastic, sure! In the meantime, I'll merge this PR since it's still a net improvement 🙃
